name: EVENT_DEMO
on: 
  pull_request:
    types: [opened, closed]
  
  worlflow_dispatch:

jobs:
  deploy:
    runs_on: ubuntu_latest
    setps:
      - name: josn event
        run: echo "run ${{toJSON(gihub.event)}}"
      - name: get code
        uses: actions/checkout@v4
      - name: installdependency
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
        run: pip install opencv-python
      - uses: check python version
        run: python --version