name: EVENT_DEMO
on: 
  pull_request:
    types: [opened, closed]
    branches:
      - main
  workflow_dispatch:
  # for filter check  workflow syntax
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: josn event
        run: echo "run ${{toJSON(github.event)}}"
      - name: get code
        uses: actions/checkout@v4
      - name: installdependency
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install opencv
        run: pip install opencv-python
      - name: check python version
        run: python --version
      - name: run python script
        run: python python_print.py